version: '3.3'
services:
  #db:
  #  image: mysqlcompose #necessarily to build firstly the Dockerfile
  #  env_file:
  #    - ./env/pass.env
  #  restart: always
  #  ports:
  #    - 3310:3306
  #  networks:
  #    - dockercompose
    
  #flask:
  #  depends_on:
  #    - db
  #  image: flaskcompose #necessarily to build firstly the Dockerfile
  #  restart: always
  #  networks:
  #    - dockercompose
  #  ports:
  #    - 5003:5003

### or call the Dockerfile's
  db:
    #image: mysqlcompose #don't need images when you have build/dockerfile param here
    env_file:
      - ./env/pass.env
    restart: always
    ports:
      - 3310:3306
    networks:
      - dockercompose
    build: 
      dockerfile: ./mysql/Dockerfile
    container_name: db_app
  flask:
    depends_on:
      - db
    #image: flaskcompose #don't need images when you have build/dockerfile param here
    restart: always
    networks:
      - dockercompose
    ports:
      - 5003:5003
    build: 
      dockerfile: ./flask/Dockerfile
    container_name: flask_app

networks:
  dockercompose:
    driver: bridge