version: '3.3'
services:
  db:
    image: mysql
    volumes:
      - db_data2:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - 3308:3306
  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - 8001:80
    restart: always
    env_file:
      - ./config/db.env
volumes:
  db_data2: {}